---
title: "Análise de TcMax"
author: "Antonio e Fernando"
date: "14-07-2015"
output: html_document
---

```{r bibliotecas, echo=FALSE, cache=TRUE, warning=FALSE, message=FALSE}
library(ggplot2)
library(reshape2)
```

# Intro
Verificar quais as variáveis estão associadas com *TcMax*.

# Análise
```{r carregando, cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
dados<-read.csv("../tese.csv", header = TRUE, sep = ";", dec = ".")
```

You can also embed plots, for example:

```{r ditr.bioma, cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.height=6, fig.width=4, fig.cap=' Distribuição de tcMax'}
ggplot(dados, aes(x = tcmax)) + geom_histogram(binwidth = 0.5) +
  geom_histogram(colour = "white") +
  geom_vline(x = mean(dados$tcmax), colour = 'blue') +
  facet_wrap( ~ localidade, scale = 'free_y', ncol = 1) + theme_bw()
```


```{r ditr.bioma.Classe, cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.height=10, fig.width=12, fig.cap=' Distribuição de tcMax'}
# ggplot(dados, aes(x = tcmax)) + geom_histogram(binwidth = 0.5) +
#   geom_histogram(colour = "white") +
#   geom_vline(x = mean(dados$tcmax), colour = 'blue') +
#   facet_grid(classe ~ localidade, scale = 'free') + theme_bw()
```

```{r ditr.Classe.bioma, cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.height=10, fig.width=12, fig.cap= ' Distribuição de tcMax'}
ggplot(dados, aes(x = tcmax)) + geom_histogram(binwidth = 0.5) +
  geom_histogram(colour = "white") +
  geom_vline(x = mean(dados$tcmax), colour = 'blue') +
  facet_grid(localidade ~ classe, scale = 'free') + theme_bw()
```

```{r ditr.temSol.bioma, cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.height=10, fig.width=12, fig.cap= ' Distribuição de TempSol'}
ggplot(dados, aes(x = tempSOL)) + geom_histogram(binwidth = 0.5) +
  geom_histogram(colour = "white") +
  geom_vline(x = mean(dados$tempSOL), colour = 'blue') +
  facet_grid(localidade ~ classe, scale = 'free') + theme_bw()
```

```{r ditr.alt.bioma, cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.height=10, fig.width=12, fig.cap= ' Distribuição de Altitude'}
ggplot(dados, aes(x = alt)) + geom_histogram(binwidth = 0.5) +
  geom_histogram(colour = "white") +
  geom_vline(x = mean(dados$alt), colour = 'blue') +
  facet_grid(localidade ~ classe, scale = 'free') + theme_bw()
```

Fizemos uma regressão simples para verificar a relação entre o **tcmax** com as variáveis **tempSOL** e **alt**.

```{r lm.tcMax, cache=TRUE, echo=TRUE}
fit.tcMax1 <- lm(dados$tcmax ~ dados$tempSOL)
summary(fit.tcMax1)

fit.tcMax2 <- lm(dados$tcmax ~ dados$tempSOL + dados$alt)
summary(fit.tcMax2)
```

```{r plot.lm1, cache=TRUE, echo=FALSE}
# plot do primeiro modelo
plot(dados$tempSOL,dados$tcmax)
abline(fit.tcMax1)
```

A regessão não ajustou bem, pois um grupo apresentou temperaturas de **tcmax** acima de 50 **tempSOL**, mas os seu **tcmax** ficou abaixo do esperado.

```{r destoantes, cache=TRUE, echo=FALSE}
segundo.grupo <- dados[which(dados$tempSOL > 50), ]
summary(segundo.grupo[,c('tcmax', 'classe','localidade','long','estacao','tempSOL')])
```



